- 1.1.14
- _NAME: MX Master 3S
  _absent: [hi-res-scroll, lowres-scroll-mode, onboard_profiles, report_rate, report_rate_extended, pointer_speed,>
    backlight_level, backlight_duration_hands_out, backlight_duration_hands_in, backlight_duration_powered, backli>
    rgb_zone_, brightness_control, per-key-lighting, fn-swap, persistent-remappable-keys, disable-keyboard-keys, c>
    m-key-leds, mr-key-led, multiplatform, gesture2-gestures, gesture2-divert, gesture2-params, sidetone, equalize>
  _battery: 4100
  _modelId: B03400000000
  _sensitive: {divert-keys: true, hires-scroll-mode: true, hires-smooth-resolution: false, reprogrammable-keys: tr>
    thumb-scroll-invert: ignore, thumb-scroll-mode: ignore}
  _serial: 9573E67F
  _unitId: 9573E67F
  _wpid: B034
  change-host: null
  divert-keys: {82: 0, 83: 1, 86: 1, 195: 1, 196: 1}
  dpi: 1000
  hires-scroll-mode: false
  hires-smooth-invert: false
  hires-smooth-resolution: false
  reprogrammable-keys: {80: 80, 81: 81, 82: 82, 83: 83, 86: 86, 195: 196, 196: 196}
  scroll-ratchet: 2
  smart-shift: 50
  thumb-scroll-invert: false
  thumb-scroll-mode: false



